### ISSUE TITLE
Decide on using OpenGL or native Android graphics libraries

### ISSUE THREAD

**Issue by adamajammary** [adamajammary/imt3673-project#1]
Votes
* Adam: Canvas (android libraries)
* Martin: Canvas
* Michael: Canvas
* Magnus: Canvas

**Comment by Hifoz** [comment]
I vote canvas, as I feel it would be more difficult using OpenGL (although I haven't looked at OpenGL for android)

As Martin implemented drawing of GameObjects using Canvas, I assume he too leans towards Canvas
