### ISSUE TITLE
Options button going partially outside of screen in main menu in landscape mode

### ISSUE THREAD

**Issue by Hifoz** [adamajammary/imt3673-project#18]
![image](https://user-images.githubusercontent.com/5193732/38744482-3380930c-3f42-11e8-956d-4f315cfb7b60.png)

Given that the game is played in landscape only, landscape support for the menues is probably a good thing to have.

**Comment by magweng** [comment]
![landscape mode](https://user-images.githubusercontent.com/31439862/38779154-ad6b1fd8-40c4-11e8-8e75-e301d8c460e3.PNG)

Added new StartupMenu layout for landscape mode
