### ISSUE TITLE
Decide on the objective of the game

### ISSUE THREAD

**Issue by adamajammary** [adamajammary/imt3673-project#2]
* [Labyrinth (marble game)](https://en.wikipedia.org/wiki/Labyrinth_(marble_game))
* Meatball
* [Agar.io](http://agar.io/)
* ?

Idea so far:
A obstacle course map, that is in 1 dimension (screen width + length) and bigger then the phone screen. The camera autoscrolls the screen along with the ball. The objective is to get the ball to some victory point in the map. The maps are designed, and go from left to right. You get points for how well you go from start to finish and medals.

**Comment by Hifoz** [comment]
Personally, I don't think something like Agar.io would be a good idea for this project, as we would have to spend time on server-side stuff that wouldn't be relevant for the other two ideas. 

Labyrinth could be interesting if we add our own features to it that the player had to use/avoid, like the holes in the original version (spring-boards that can fire you over a wall, portals taking you to the other side of the map, a trap that flips gravity/movement, just to mention a few possibilities).

The Meatball thing also sounded like it could be good, but as we haven't really discussed much, it's hard to pinpoint where exactly we want to go with it.

**Comment by Muff1nz** [comment]
1D or 2D panning of the map that is bigger then the phone screen?
Votes:
Adam: ?
Magnus: ?
Michael: ?
Martin: 1D

**Comment by Hifoz** [comment]
!vote 2d

**Comment by Muff1nz** [comment]
Generate maps or design maps?
Adam: ?
Magnus: ?
Michael: ?
Martin: ?

**Comment by magweng** [comment]
!vote 2d

**Comment by Muff1nz** [comment]
Obstacle course or labrynth?

**Comment by Muff1nz** [comment]
!vote obstacle course

**Comment by adamajammary** [comment]
!vote obstacle course (kanskje enklere å designe?)

**Comment by magweng** [comment]
!vote obstacle course
